### ISSUE TITLE
error: no matching member function for call to 'insert'

### ISSUE THREAD

**Issue by jplatte** [minecraft-linux/libc-shim#36]
Previously reported at https://github.com/minecraft-linux/mcpelauncher-manifest/issues/1028, but I think it only affects this library.

Trying to build with clang 18.1.8 (on arch linux), one gets a couple of the following errors:

<details><summary>Error message</summary>

```
/home/jplatte/.cache/paru/clone/mcpelauncher-linux-git/src/mcpelauncher-manifest/libc-shim/src/common.cpp:955:10: error: no matching member function for call to 'insert'
  955 |     list.insert(list.end(), {
      |     ~~~~~^~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1364:7: note: candidate function not viable: cannot convert initializer list argument to 'const value_type' (aka 'const shim::shimmed_symbol')
 1364 |       insert(const_iterator __position, const value_type& __x);
      |       ^                                 ~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1395:7: note: candidate function not viable: cannot convert initializer list argument to 'value_type' (aka 'shim::shimmed_symbol')
 1395 |       insert(const_iterator __position, value_type&& __x)
      |       ^                                 ~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1413:7: note: candidate function not viable: cannot convert initializer list argument to 'shim::shimmed_symbol'
 1413 |       insert(const_iterator __position, initializer_list<value_type> __l)
      |       ^                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1439:7: note: candidate function not viable: requires 3 arguments, but 2 were provided
 1439 |       insert(const_iterator __position, size_type __n, const value_type& __x)
      |       ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/stl_vector.h:1484:2: note: candidate function template not viable: requires 3 arguments, but 2 were provided
 1484 |         insert(const_iterator __position, _InputIterator __first,
      |         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1485 |                _InputIterator __last)
      |                ~~~~~~~~~~~~~~~~~~~~~
```

</details>

Knowing C++ myself, I went and inserted `shim::shimmed_symbol` before the inner initializer lists that are passed as one big initializer list to insert, to give the compiler a nudge to produce a better error message. And it did:

```
/home/jplatte/.cache/paru/clone/mcpelauncher-linux-git/src/mcpelauncher-manifest/libc-shim/src/cstdio.cpp:199:9: error: no matching constructor for initialization of 'shim::shimmed_symbol'
  199 |         shim::shimmed_symbol{"printf", ::printf},
      |         ^                   ~~~~~~~~~~~~~~~~~~~~
/home/jplatte/.cache/paru/clone/mcpelauncher-linux-git/src/mcpelauncher-manifest/libc-shim/include/libc_shim.h:12:9: note: candidate constructor not viable: no overload of 'printf' matching 'void *' for 2nd argument
   12 |         shimmed_symbol(const char *name, void *value)
      |         ^                                ~~~~~~~~~~~
/home/jplatte/.cache/paru/clone/mcpelauncher-linux-git/src/mcpelauncher-manifest/libc-shim/include/libc_shim.h:16:9: note: candidate template ignored: couldn't infer template argument 'Ret'
   16 |         shimmed_symbol(const char *name, Ret (*ptr)(Args...))
      |         ^
```

Idk whether clang is right or wrong to fail inference there, but I think this code is kind of wrong either way to rely so much on inference. I'm unsure how to really fix it though... Hope this small dive into the problem can act as a good starting point for somebody who is more familiar with the codebase.

**Comment by jplatte** [comment]
Hm, I see the `PKGBUILD` already tries to disable `fortify-source`, I bet the `sed` replacement just doesn't match for some reason. Thanks for the hint, I'll dig into it a little more when I get the time!

Anyways, sounds like you're not intending to be compatible with those compiler flags so I'll close this.

**Comment by xiota** [comment]
AUR maintainer updated package to remove `_FORTIFY_SOURCE` from default build flags.  Confirmed working a few days ago.  Existence of issues containing pointers to solution for people to find should be sufficient.

Related: #33

**Comment by xiota** [comment]
@jplatte I successfully built the AUR package from latest commit a couple days ago.  From `.cache/paru/clone` in your post, you may need to clear cache.  If that doesn't work, try building in clean chroot.

**Comment by jplatte** [comment]
I think it might be related to my `/etc/makepkg.conf` that diverged a bit from upstream. I just copied over the `.pacnew` file and am trying again (with the non-`git` packages, since I saw they were recently updated).
